package com.cg.dao;

import java.util.List;

import com.cg.dto.Feedback;
import com.cg.exception.FeedbackNotFoundException;

public interface FeedbackDao {

	String byMonth = "SELECT TM.TRAINING_CODE, TM.START_DATE, TM.END_DATE, EM.EMPLOYEE_NAME, EM1.EMPLOYEE_NAME, FM.FB_PRS_COMM, FM.FB_CLRFY_DBTS, FM.FB_TM, FM.FB_HND_OUT, FM.FB_HW_SW_NTWRK FROM TRAINING_MASTER TM, EMPLOYEE_MASTER EM, EMPLOYEE_MASTER EM1, FEEDBACK_MASTER FM WHERE TM.FACULTY_CODE = EM.EMPLOYEE_ID AND TM.TRAINING_CODE = FM.TRAINING_CODE AND EM1.EMPLOYEE_ID = FM.PARTICIPANT_ID AND EXTRACT(MONTH FROM END_DATE)=?";
	
	String byFacultyAndMonth = "SELECT TM.TRAINING_CODE, TM.START_DATE, TM.END_DATE, EM.EMPLOYEE_NAME, EM1.EMPLOYEE_NAME, FM.FB_PRS_COMM, FM.FB_CLRFY_DBTS, FM.FB_TM, FM.FB_HND_OUT, FM.FB_HW_SW_NTWRK FROM TRAINING_MASTER TM, EMPLOYEE_MASTER EM, EMPLOYEE_MASTER EM1, FEEDBACK_MASTER FM WHERE TM.FACULTY_CODE = EM.EMPLOYEE_ID AND TM.TRAINING_CODE = FM.TRAINING_CODE AND EM1.EMPLOYEE_ID = FM.PARTICIPANT_ID AND EXTRACT(MONTH FROM END_DATE)=? AND TM.FACULTY_ID = ?"; 
	
	String feedbackDefaulters = "SELECT TM.TRAINING_CODE, TM.START_DATE, TM.END_DATE, EM.EMPLOYEE_NAME, FM.FB_PRS_COMM, FM.FB_CLRFY_DBTS, FM.FB_TM, FM.FB_HND_OUT, FM.FB_HW_SW_NTWRK FROM TRAINING_MASTER TM, EMPLOYEE_MASTER EM, FEEDBACK_MASTER FM WHERE TM.FACULTY_CODE = EM.EMPLOYEE_ID AND TM.TRAINING_CODE = FM.TRAINING_CODE AND EXTRACT(MONTH FROM END_DATE)=? AND (FM.FB_PRS_COMM = NULL OR FM.FB_CLRFY_DBTS = NULL OR FM.FB_TM = NULL OR FM.FB_HND_OUT =NULL OR FM.FB_HW_SW_NTWRK = NULL OR FM.COMMENTS = NULL )";
	
	List<Feedback> byMonth(int month) throws FeedbackNotFoundException;
	
	List<Feedback> byFacultyForMonth(int facultyCode, int month) throws FeedbackNotFoundException;
	
	List<Feedback> feedbackDefaultersByMonth(int month) throws FeedbackNotFoundException;
	
}
